package com.rong.persist.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("ip_temp", "id", IpTemp.class);
		arp.addMapping("qq_data", "id", QqData.class);
		arp.addMapping("qq_data_base", "id", QqDataBase.class);
		arp.addMapping("qq_data_base_history", "id", QqDataBaseHistory.class);
		arp.addMapping("qq_team", "id", QqTeam.class);
		arp.addMapping("qq_update_pwd_wait", "id", QqUpdatePwdWait.class);
		arp.addMapping("report_qq", "id", ReportQq.class);
		arp.addMapping("system_admin", "id", SystemAdmin.class);
		arp.addMapping("system_config", "id", SystemConfig.class);
		arp.addMapping("system_resource", "id", SystemResource.class);
		arp.addMapping("system_role", "id", SystemRole.class);
		arp.addMapping("system_role_resource", "id", SystemRoleResource.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_pwderror_statis", "id", UserPwderrorStatis.class);
		arp.addMapping("user_token", "id", UserToken.class);
	}
}

