package com.rong.persist.model;

import com.rong.persist.model.base.BaseIpTemp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class IpTemp extends BaseIpTemp<IpTemp> {
	public static final IpTemp dao = new IpTemp().dao();
	public static final String TABLE = "ip_temp";
}
