package com.rong.persist.model;

import com.rong.persist.model.base.BaseQqGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QqGroup extends BaseQqGroup<QqGroup> {
	public static final QqGroup dao = new QqGroup().dao();
	public static final String TABLE = "qq_group";
}
