package com.rong.persist.model;

import com.rong.persist.model.base.BaseQqTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QqTeam extends BaseQqTeam<QqTeam> {
	public static final QqTeam dao = new QqTeam().dao();
	public static final String TABLE = "qq_team";
}
