package com.rong.persist.model;

import com.rong.persist.model.base.BaseQqUpdatePwdWait;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QqUpdatePwdWait extends BaseQqUpdatePwdWait<QqUpdatePwdWait> {
	public static final QqUpdatePwdWait dao = new QqUpdatePwdWait().dao();
	public static final String TABLE = "qq_update_pwd_wait";
}
