package com.rong.persist.model;

import com.rong.persist.model.base.BaseSystemConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemConfig extends BaseSystemConfig<SystemConfig> {
	public static final SystemConfig dao = new SystemConfig().dao();
	public static final String TABLE = "system_config";
}
