package com.rong.persist.model;

import com.rong.persist.model.base.BaseSystemRoleResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemRoleResource extends BaseSystemRoleResource<SystemRoleResource> {
	public static final SystemRoleResource dao = new SystemRoleResource().dao();
	public static final String TABLE = "system_role_resource";
}
