package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQqTeam<M extends BaseQqTeam<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setTeamName(java.lang.String teamName) {
		set("team_name", teamName);
	}

	public java.lang.String getTeamName() {
		return getStr("team_name");
	}

	public void setCostPrice(java.lang.Double costPrice) {
		set("cost_price", costPrice);
	}

	public java.lang.Double getCostPrice() {
		return getDouble("cost_price");
	}

	public void setQqCount(java.lang.Integer qqCount) {
		set("qq_count", qqCount);
	}

	public java.lang.Integer getQqCount() {
		return getInt("qq_count");
	}

	public void setQqCountLived(java.lang.Integer qqCountLived) {
		set("qq_count_lived", qqCountLived);
	}

	public java.lang.Integer getQqCountLived() {
		return getInt("qq_count_lived");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
