package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
	}

	public java.lang.String getNickName() {
		return getStr("nick_name");
	}

	public void setUserHead(java.lang.String userHead) {
		set("user_head", userHead);
	}

	public java.lang.String getUserHead() {
		return getStr("user_head");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setUserPassword(java.lang.String userPassword) {
		set("user_password", userPassword);
	}

	public java.lang.String getUserPassword() {
		return getStr("user_password");
	}

	public void setPayPassword(java.lang.String payPassword) {
		set("pay_password", payPassword);
	}

	public java.lang.String getPayPassword() {
		return getStr("pay_password");
	}

	public void setUserType(java.lang.Boolean userType) {
		set("user_type", userType);
	}

	public java.lang.Boolean getUserType() {
		return get("user_type");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setSex(java.lang.Boolean sex) {
		set("sex", sex);
	}

	public java.lang.Boolean getSex() {
		return get("sex");
	}

	public void setState(java.lang.Integer state) {
		set("state", state);
	}

	public java.lang.Integer getState() {
		return getInt("state");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
