package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseQqData<M extends BaseQqData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setQq(java.lang.String qq) {
		set("qq", qq);
	}

	public java.lang.String getQq() {
		return getStr("qq");
	}

	public void setQqPwd(java.lang.String qqPwd) {
		set("qq_pwd", qqPwd);
	}

	public java.lang.String getQqPwd() {
		return getStr("qq_pwd");
	}

	public void setQqType(java.lang.Integer qqType) {
		set("qq_type", qqType);
	}

	public java.lang.Integer getQqType() {
		return getInt("qq_type");
	}

	public void setTeamId(java.lang.Long teamId) {
		set("team_id", teamId);
	}

	public java.lang.Long getTeamId() {
		return getLong("team_id");
	}

	public void setTeamName(java.lang.String teamName) {
		set("team_name", teamName);
	}

	public java.lang.String getTeamName() {
		return getStr("team_name");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

	public java.lang.String getTags() {
		return getStr("tags");
	}

	public void setLoginCount(java.lang.Integer loginCount) {
		set("login_count", loginCount);
	}

	public java.lang.Integer getLoginCount() {
		return getInt("login_count");
	}

	public void setState(java.lang.Boolean state) {
		set("state", state);
	}

	public java.lang.Boolean getState() {
		return get("state");
	}

	public void setOutStorageTime(java.util.Date outStorageTime) {
		set("out_storage_time", outStorageTime);
	}

	public java.util.Date getOutStorageTime() {
		return get("out_storage_time");
	}

	public void setInStorageTime(java.util.Date inStorageTime) {
		set("in_storage_time", inStorageTime);
	}

	public java.util.Date getInStorageTime() {
		return get("in_storage_time");
	}

	public void setOutStorageDays(java.lang.Integer outStorageDays) {
		set("out_storage_days", outStorageDays);
	}

	public java.lang.Integer getOutStorageDays() {
		return getInt("out_storage_days");
	}

	public void setLoginTime(java.util.Date loginTime) {
		set("login_time", loginTime);
	}

	public java.util.Date getLoginTime() {
		return get("login_time");
	}

	public void setQqAge(java.lang.Integer qqAge) {
		set("qq_age", qqAge);
	}

	public java.lang.Integer getQqAge() {
		return getInt("qq_age");
	}

}
