package com.rong.persist.model;

import com.rong.persist.model.base.BaseApp;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class App extends BaseApp<App> {
	public static final App dao = new App().dao();
}
