package com.rong.persist.model;

import com.rong.persist.model.base.BaseQqData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QqData extends BaseQqData<QqData> {
	public static final QqData dao = new QqData().dao();
}
