package com.rong.persist.model;

import com.rong.persist.model.base.BaseQqDataBase;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QqDataBase extends BaseQqDataBase<QqDataBase> {
	public static final QqDataBase dao = new QqDataBase().dao();
}
