package com.rong.persist.model;

import com.rong.persist.model.base.BaseQqDataBaseHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QqDataBaseHistory extends BaseQqDataBaseHistory<QqDataBaseHistory> {
	public static final QqDataBaseHistory dao = new QqDataBaseHistory().dao();
}
