package com.rong.persist.model;

import com.rong.persist.model.base.BaseReportQq;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReportQq extends BaseReportQq<ReportQq> {
	public static final ReportQq dao = new ReportQq().dao();
}
