package com.rong.persist.model;

import com.rong.persist.model.base.BaseSystemRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemRole extends BaseSystemRole<SystemRole> {
	public static final SystemRole dao = new SystemRole().dao();
}
