package com.rong.persist.model;

import com.rong.persist.model.base.BaseSystemAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemAdmin extends BaseSystemAdmin<SystemAdmin> {
	public static final SystemAdmin dao = new SystemAdmin().dao();
}
