package com.rong.persist.model;

import com.rong.persist.model.base.BaseSystemResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemResource extends BaseSystemResource<SystemResource> {
	public static final SystemResource dao = new SystemResource().dao();
}
