package com.rong.persist.model;

import com.rong.persist.model.base.BaseUserToken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserToken extends BaseUserToken<UserToken> {
	public static final UserToken dao = new UserToken().dao();
}
