package com.rong.persist.model;

import com.rong.persist.model.base.BaseUserPwderrorStatis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserPwderrorStatis extends BaseUserPwderrorStatis<UserPwderrorStatis> {
	public static final UserPwderrorStatis dao = new UserPwderrorStatis().dao();
}
