package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseVersion<M extends BaseVersion<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setVersionName(java.lang.String versionName) {
		set("version_name", versionName);
	}

	public java.lang.String getVersionName() {
		return getStr("version_name");
	}

	public void setSystemType(java.lang.Integer systemType) {
		set("system_type", systemType);
	}

	public java.lang.Integer getSystemType() {
		return getInt("system_type");
	}

	public void setDownloadUrl(java.lang.String downloadUrl) {
		set("download_url", downloadUrl);
	}

	public java.lang.String getDownloadUrl() {
		return getStr("download_url");
	}

	public void setIconUrl(java.lang.String iconUrl) {
		set("icon_url", iconUrl);
	}

	public java.lang.String getIconUrl() {
		return getStr("icon_url");
	}

	public void setFileSize(java.lang.Long fileSize) {
		set("file_size", fileSize);
	}

	public java.lang.Long getFileSize() {
		return getLong("file_size");
	}

	public void setAppVersion(java.lang.String appVersion) {
		set("app_version", appVersion);
	}

	public java.lang.String getAppVersion() {
		return getStr("app_version");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setIsPublish(java.lang.Boolean isPublish) {
		set("is_publish", isPublish);
	}

	public java.lang.Boolean getIsPublish() {
		return get("is_publish");
	}

	public void setAutoDownload(java.lang.Boolean autoDownload) {
		set("auto_download", autoDownload);
	}

	public java.lang.Boolean getAutoDownload() {
		return get("auto_download");
	}

	public void setIsFile(java.lang.Boolean isFile) {
		set("is_file", isFile);
	}

	public java.lang.Boolean getIsFile() {
		return get("is_file");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setAppId(java.lang.Long appId) {
		set("app_id", appId);
	}

	public java.lang.Long getAppId() {
		return getLong("app_id");
	}

	public void setAppName(java.lang.String appName) {
		set("app_name", appName);
	}

	public java.lang.String getAppName() {
		return getStr("app_name");
	}

	public void setAppCode(java.lang.String appCode) {
		set("app_code", appCode);
	}

	public java.lang.String getAppCode() {
		return getStr("app_code");
	}

}
