package com.rong.persist.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("appv_app", "id", App.class);
		arp.addMapping("appv_version", "id", Version.class);
		arp.addMapping("system_admin", "id", SystemAdmin.class);
		arp.addMapping("system_config", "id", SystemConfig.class);
		arp.addMapping("system_resource", "id", SystemResource.class);
		arp.addMapping("system_role", "id", SystemRole.class);
		arp.addMapping("system_role_resource", "id", SystemRoleResource.class);
	}
}

